# Calcula matrizes

In [2]:
import numpy as np

# Criar as matrizes A e B
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

B_transposta = B.T  # transpor B para ter dimensões 2x3

# multiplicação de matrizes
resultado = np.dot(A, B_transposta)

# exibindo o resultado
print("Matriz A:")
print(A)

print("\nMatriz B (Transposta):")
print(B_transposta)

print("\nResultado da multiplicação A * B^T:")
print(resultado)


Matriz A:
[[1 2]
 [3 4]
 [5 6]]

Matriz B (Transposta):
[[ 7  9 11]
 [ 8 10 12]]

Resultado da multiplicação A * B^T:
[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]]
